version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: zubizu
      WORDPRESS_DB_PASSWORD: Ss88047062*101
      WORDPRESS_DB_NAME: wp
      WP_DEBUG: 'true'
    networks:
      - wordpress-net

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Ss88047062*101
      MYSQL_DATABASE: wp
      MYSQL_USER: zubizu
      MYSQL_PASSWORD: Ss88047062*101
    ports:
      - "3308:3306"
    networks:
      - wordpress-net

networks:
  wordpress-net:
    driver: bridge
